version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres-local
    environment:
      - POSTGRES_USER=rully
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=blog_api
    ports:
      - "55432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
