version: '3.8'

services:
  db:
    container_name: pg_local
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "54432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_local
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5555:80"
